"""
Fetches FOMC statements and minutes directly from the Federal Reserve website.

Calendar page: https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm
  - Statements : href contains "monetary"   AND ends with "a.htm"
  - Minutes    : href contains "fomcminutes" AND ends with ".htm"

Date is extracted from the 8-digit number in each URL (e.g. 20260128 → 2026-01).
Statement text is fetched once per page; summaries are generated by Claude Haiku
and persisted in .data/fed_summaries.json so each page is only ever summarised once.
"""

import re
import logging
import concurrent.futures
from datetime import datetime

import anthropic
import requests

import cache
import fetchers.summary_store as summary_store
from config import DEFAULT_START_DATE, ANTHROPIC_API_KEY

logger = logging.getLogger(__name__)

BASE_URL     = "https://www.federalreserve.gov"
CALENDAR_URL = f"{BASE_URL}/monetarypolicy/fomccalendars.htm"
SUMMARIZE_CHARS = 8000   # feed at most this many chars to Claude
MAX_WORKERS     = 6      # parallel page fetches on first run

TYPE_TO_CAT = {
    "Statement": "cb",
    "Minutes":   "speech",
}

SUMMARY_PROMPT = (
    "Summarise this Federal Reserve communication in 2-3 sentences. "
    "Focus on the key policy decision, rate action, or major insight. "
    "Be concise and factual."
)


# ── helpers ──────────────────────────────────────────────────────────────────

def _extract_date(url: str):
    """Return (YYYY-MM-DD, YYYYMMDD) from a URL, or (None, None) if no date found."""
    m = re.search(r'(\d{8})', url)
    if not m:
        return None, None
    raw = m.group(1)
    return f"{raw[:4]}-{raw[4:6]}-{raw[6:8]}", raw


def _make_title(event_type: str, raw_date: str) -> str:
    try:
        dt = datetime.strptime(raw_date, "%Y%m%d")
        day = dt.day
        human = dt.strftime(f"%B {day}, %Y")
        return f"FOMC {event_type} – {human}"
    except ValueError:
        return f"FOMC {event_type}"


def _fetch_page_text(url: str) -> str:
    """Fetch a Fed HTML page and return only the policy content, stripped of nav/boilerplate."""
    resp = requests.get(url, timeout=15)
    resp.raise_for_status()
    html = resp.text

    def clean(raw: str) -> str:
        return re.sub(r'\s+', ' ', re.sub(r'<[^>]+>', ' ', raw)).strip()

    # Strategy 1: statement pages — content sits in the 8-col main div
    m = re.search(
        r'<div class="col-xs-12 col-sm-8 col-md-8">(.*?)</div>\s*<div class="col-xs-12 col-sm-4',
        html, re.S
    )
    if m:
        return clean(m.group(1))

    # Strategy 2: minutes pages — find where the minutes text begins
    for anchor in ("Minutes of the Federal", "A joint meeting of the Federal"):
        idx = html.find(anchor)
        if idx > 0:
            return clean(html[idx: idx + 15000])

    # Strategy 3: last-resort — any mention of the committee
    idx = html.find("Federal Open Market Committee")
    if idx > 0:
        return clean(html[idx: idx + 10000])

    return clean(html)[:10000]


# ── calendar scrape ───────────────────────────────────────────────────────────

def _get_fomc_links(cutoff: str) -> list[dict]:
    """
    Scrape the FOMC calendar and return a sorted list of matching links since cutoff.

    Statements: href contains "monetary" and ends with "a.htm".
                Date comes from the 8-digit number in the URL (= meeting/release date).

    Minutes:    href contains "fomcminutes" and ends with ".htm".
                Date comes from the "(Released %B %d, %Y)" text that follows the link
                on the page — the URL date is the meeting date, not the publication date.
    """
    resp = requests.get(CALENDAR_URL, timeout=15)
    resp.raise_for_status()
    html = resp.text

    seen  = set()
    links = []

    # ── Statements ────────────────────────────────────────────────────────────
    for m in re.finditer(
        r'href=["\']([^"\'#?]*monetary\d{8}a\.htm)["\']',
        html, re.IGNORECASE
    ):
        href = m.group(1)
        iso, raw = _extract_date(href)
        if not iso or iso[:7] < cutoff:
            continue
        key = (raw, 'Statement')
        if key in seen:
            continue
        seen.add(key)
        full_url = (BASE_URL + href) if href.startswith('/') else href
        links.append({
            "url":        full_url,
            "d":          iso,       # YYYY-MM-DD — exact day for chart alignment
            "raw_date":   raw,
            "cat":        TYPE_TO_CAT['Statement'],
            "event_type": 'Statement',
            "title":      _make_title('Statement', raw),
        })

    # ── Minutes ───────────────────────────────────────────────────────────────
    # Capture href + the "Released %B %d, %Y" text that follows the <br> tag
    for m in re.finditer(
        r'href=["\']([^"\']*fomcminutes\d{8}\.htm)["\']'
        r'\s*>[^<]*</a>'               # close the <a> tag (link text is "HTML")
        r'[^<]*<br>\s*\(Released\s+([^)]+)\)',
        html, re.IGNORECASE
    ):
        href         = m.group(1)
        release_text = m.group(2).strip()   # e.g. "February 18, 2026"
        _, raw_url   = _extract_date(href)  # meeting date from URL (for dedup only)
        if not raw_url:
            continue

        try:
            release_dt = datetime.strptime(release_text, "%B %d, %Y")
            iso    = release_dt.strftime("%Y-%m-%d")   # YYYY-MM-DD
            raw    = release_dt.strftime("%Y%m%d")
            title  = _make_title('Minutes', raw)
        except ValueError:
            logger.warning("Could not parse minutes release date: %r", release_text)
            continue

        if iso[:7] < cutoff:
            continue
        key = (raw_url, 'Minutes')     # dedup on URL meeting date
        if key in seen:
            continue
        seen.add(key)

        full_url = (BASE_URL + href) if href.startswith('/') else href
        links.append({
            "url":        full_url,
            "d":          iso,       # YYYY-MM-DD — exact release day for chart alignment
            "raw_date":   raw,
            "cat":        TYPE_TO_CAT['Minutes'],
            "event_type": 'Minutes',
            "title":      title,
        })

    return sorted(links, key=lambda x: (x["d"], x["event_type"]))


# ── summarisation ─────────────────────────────────────────────────────────────

def _summarize_one(text: str) -> str:
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    resp = client.messages.create(
        model="claude-haiku-4-5",
        max_tokens=150,
        messages=[{
            "role": "user",
            "content": f"{SUMMARY_PROMPT}\n\n{text[:SUMMARIZE_CHARS]}"
        }]
    )
    result = resp.content[0].text.strip()
    # strip any markdown heading Haiku may prepend
    if result.startswith("#"):
        result = result.split("\n", 1)[-1].strip()
    return result


def _fetch_and_summarize(link: dict, db: dict) -> tuple[str, str]:
    """Fetch the page, summarise it, return (store_key, summary). Used in thread pool."""
    try:
        text = _fetch_page_text(link["url"])
        key  = summary_store.key_for(text)
        if key in db:
            return key, db[key]
        summary = _summarize_one(text)
        return key, summary
    except Exception as e:
        logger.error("Failed to fetch/summarise %s: %s", link["url"], e)
        return None, None


# ── main entry point ──────────────────────────────────────────────────────────

def fetch(start_date=DEFAULT_START_DATE, force=False):
    cache_key = f"fed_events_{start_date[:7]}"
    if not force:
        cached = cache.get(cache_key)
        if cached is not None:
            return cached

    cutoff = start_date[:7]
    logger.info("Scraping FOMC calendar from federalreserve.gov since %s", cutoff)
    links = _get_fomc_links(cutoff)
    logger.info("Found %d FOMC items (statements + minutes)", len(links))

    db = summary_store.load_all()

    # Determine which links still need a page fetch + summary
    # We can't know the store key without the page text, so we fetch all pages
    # that don't already have a stored summary keyed by URL-derived identity.
    # We use a secondary index: url → store_key, stored inside the db as a
    # lightweight "url_index" entry (prefix "url:").
    def url_key(url): return f"url:{url}"

    missing = [lk for lk in links if url_key(lk["url"]) not in db]

    if missing:
        logger.info("Fetching + summarising %d new FOMC pages with Claude Haiku…", len(missing))
        new_entries = {}
        with concurrent.futures.ThreadPoolExecutor(max_workers=MAX_WORKERS) as pool:
            futures = {pool.submit(_fetch_and_summarize, lk, db): lk for lk in missing}
            for fut in concurrent.futures.as_completed(futures):
                lk  = futures[fut]
                key, summary = fut.result()
                if key and summary:
                    new_entries[key]               = summary
                    new_entries[url_key(lk["url"])] = key   # url → content key

        if new_entries:
            db.update(new_entries)
            summary_store.save_all(db)
            logger.info("Summary store updated (%d total entries)", len(db))

    # Build final event list
    events = []
    for lk in links:
        uk = url_key(lk["url"])
        content_key = db.get(uk)
        body = db.get(content_key, "") if content_key else ""
        events.append({
            "d":     lk["d"],
            "cat":   lk["cat"],
            "title": lk["title"],
            "body":  body or f"[Content unavailable for {lk['title']}]",
        })

    events.sort(key=lambda e: (e["d"], e["cat"]))
    cache.set(cache_key, events)
    logger.info("Fed events ready: %d items from %s", len(events), cutoff)
    return events
